---
- name: Include OS-specific variables.
  include_vars: "main.yml"

- name: Check if apache2 is installed
  command: dpkg-query -l apache2
  register: deb_check
  failed_when: false
  changed_when: false

- name: Add apache envvars.
  template:
    src: "envvars.conf.j2"
    dest: "{{ apache_conf_path }}/envvars"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: deb_check.stderr.lower().find('no packages found') < 0
